/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Bytes {
  static new(): Bytes
  static fromBytes(data: Uint8Array): Bytes
  static fromString(value: string): Bytes
  get isEmpty(): boolean
  get len(): number
  toBytes(): Uint8Array
  toString(): string
}

export declare class CancellationToken {
  constructor()
  /**
   * Interrupt all associated get queries.
   *
   * Resolves once cancellation completes. On failure, some operations might
   * not be cancelled.
   */
  cancel(): Promise<void>
  /** Returns true if the token was cancelled (i.e. `cancel` was called). */
  get isCancelled(): boolean
}

export declare class Config {
  /** The default configuration, used to open a session. */
  static default(): Config
  /** The default environment variable containing the file path used in `fromEnv`. */
  static defaultConfigPathEnv(): string
  /**
   * Load configuration from the file path specified in the
   * `defaultConfigPathEnv` environment variable.
   */
  static fromEnv(): Config
  /** Load configuration from the file at `path`. */
  static fromFile(path: string): Config
  /** Load configuration from the JSON5 string `input`. */
  static fromJson5(input: string): Config
  /** Returns a JSON string containing the configuration at `key`. */
  getJson(key: string): string
  /** Inserts configuration value `value` at `key`. */
  insertJson5(key: string, value: string): void
  /** Removes the configuration value at `key`. */
  remove(key: string): void
}

/**
 * Streaming deserializer implementing the Zenoh serialization format.
 *
 * Read values in the same order they were written. Use `done` to check whether
 * the buffer is fully consumed.
 */
export declare class Deserializer {
  constructor(data: Bytes)
  /** `true` when there is no data left to deserialize. */
  get done(): boolean
  i8(): number
  i16(): number
  i32(): number
  u8(): number
  u16(): number
  u32(): number
  i64(): bigint
  u64(): bigint
  i128(): bigint
  u128(): bigint
  f32(): number
  f64(): number
  bool(): boolean
  string(): string
  bytes(): Uint8Array
  stringArray(): Array<string>
  int8Array(): Int8Array
  int16Array(): Int16Array
  int32Array(): Int32Array
  uint16Array(): Uint16Array
  uint32Array(): Uint32Array
  float32Array(): Float32Array
  float64Array(): Float64Array
  bigInt64Array(): BigInt64Array
  bigUint64Array(): BigUint64Array
  /**
   * Deserialize an LEB128 variable-length non-negative integer (the count prefix
   * written by `serializeVarint`).
   */
  varint(): bigint
}

export declare class Encoding {
  static default(): Encoding
  static from(value: string): Encoding
  static zenohBytes(): Encoding
  static zenohString(): Encoding
  static zenohSerialized(): Encoding
  static applicationOctetStream(): Encoding
  static textPlain(): Encoding
  static applicationJson(): Encoding
  static textJson(): Encoding
  static applicationCdr(): Encoding
  static applicationCbor(): Encoding
  static applicationYaml(): Encoding
  static textYaml(): Encoding
  static textJson5(): Encoding
  static applicationPythonSerializedObject(): Encoding
  static applicationProtobuf(): Encoding
  static applicationJavaSerializedObject(): Encoding
  static applicationOpenmetricsText(): Encoding
  static imagePng(): Encoding
  static imageJpeg(): Encoding
  static imageGif(): Encoding
  static imageBmp(): Encoding
  static imageWebp(): Encoding
  static applicationXml(): Encoding
  static applicationXWwwFormUrlencoded(): Encoding
  static textHtml(): Encoding
  static textXml(): Encoding
  static textCss(): Encoding
  static textJavascript(): Encoding
  static textMarkdown(): Encoding
  static textCsv(): Encoding
  static applicationSql(): Encoding
  static applicationCoapPayload(): Encoding
  static applicationJsonPatchJson(): Encoding
  static applicationJsonSeq(): Encoding
  static applicationJsonpath(): Encoding
  static applicationJwt(): Encoding
  static applicationMp4(): Encoding
  static applicationSoapXml(): Encoding
  static applicationYang(): Encoding
  static audioAac(): Encoding
  static audioFlac(): Encoding
  static audioMp4(): Encoding
  static audioOgg(): Encoding
  static audioVorbis(): Encoding
  static videoH261(): Encoding
  static videoH263(): Encoding
  static videoH264(): Encoding
  static videoH265(): Encoding
  static videoH266(): Encoding
  static videoMp4(): Encoding
  static videoOgg(): Encoding
  static videoRaw(): Encoding
  static videoVp8(): Encoding
  static videoVp9(): Encoding
  toString(): string
  withSchema(value: string): Encoding
}

export declare class EndPoint {
  /**
   * Parses an endpoint from its canonical string form
   * `<protocol>/<address>[?<metadata>][#<config>]`.
   */
  constructor(s: string)
  /** The protocol of this endpoint. */
  get protocol(): string
  /** The address of this endpoint. */
  get address(): string
  /** The canonical string form of this endpoint. */
  get asStr(): string
  /** The metadata view of this endpoint. */
  metadata(): Metadata
  /** The config substring of this endpoint in its canonical string form. */
  config(): string
  /**
   * Splits this endpoint into its `protocol`, `address`, `metadata` and
   * `config` string components.
   */
  split(): EndPointParts
  /** Demotes this endpoint to a `Locator`, dropping any config component. */
  toLocator(): Locator
}

export declare class EntityGlobalId {
  get zid(): string
  get eid(): number
}

export declare class FifoChannelHandlerHello {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<Hello>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): Hello | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<Hello>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Hello | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Hello | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<Hello>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): HelloStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerHello): boolean
}

export declare class FifoChannelHandlerLinkEvent {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<LinkEvent>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): LinkEvent | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<LinkEvent>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<LinkEvent | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<LinkEvent | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<LinkEvent>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): LinkEventStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerLinkEvent): boolean
}

export declare class FifoChannelHandlerMatchingStatus {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<MatchingStatus>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): MatchingStatus | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<MatchingStatus>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<MatchingStatus | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<MatchingStatus | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<MatchingStatus>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): MatchingStatusStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerMatchingStatus): boolean
}

export declare class FifoChannelHandlerMiss {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<Miss>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): Miss | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<Miss>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Miss | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Miss | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<Miss>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): MissStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerMiss): boolean
}

export declare class FifoChannelHandlerQuery {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<Query>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): Query | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<Query>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Query | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Query | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<Query>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): QueryStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerQuery): boolean
}

export declare class FifoChannelHandlerReply {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<Reply>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): Reply | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<Reply>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Reply | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Reply | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<Reply>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): ReplyStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerReply): boolean
}

export declare class FifoChannelHandlerSample {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<Sample>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): Sample | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<Sample>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Sample | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Sample | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<Sample>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): SampleStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerSample): boolean
}

export declare class FifoChannelHandlerTransportEvent {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the channel is disconnected (the producer has been dropped).
   */
  recvAsync(): Promise<TransportEvent>
  /**
   * Receives a value without blocking, returning `null` if the channel is
   * currently empty.
   */
  tryRecv(): TransportEvent | null
  /**
   * Resolves with the next value once one is available, rejecting if the
   * channel disconnects (all senders dropped). Unlike `recvAsync`, zenoh's
   * `recv` is a synchronous blocking call; it is run on a worker thread so
   * the wait never freezes the JS event loop.
   */
  recv(): Promise<TransportEvent>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects if the channel disconnects. The blocking wait
   * runs on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<TransportEvent | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects if the channel disconnects. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<TransportEvent | null>
  /**
   * Takes every value currently queued and returns them as an array,
   * without blocking. Unlike repeated `tryRecv`, no further values are
   * fetched from the channel once this snapshot is taken.
   */
  drain(): Array<TransportEvent>
  /**
   * Returns an async-iterator object over the channel, for use with
   * `for await`. The handler itself is not iterable; iteration lives here.
   */
  stream(): TransportEventStream
  /** The number of values currently queued. */
  get len(): number
  /** The channel's bound, or `null` if unbounded. */
  get capacity(): number | null
  /** Whether the channel currently holds no values. */
  get isEmpty(): boolean
  /** Whether the channel is currently at capacity. */
  get isFull(): boolean
  /** The number of senders feeding this channel. */
  get senderCount(): number
  /** The number of receivers sharing this channel. */
  get receiverCount(): number
  /** Whether the channel has been disconnected (all senders dropped). */
  get isDisconnected(): boolean
  /** Whether `other` is a handle to the same underlying channel. */
  sameChannel(other: FifoChannelHandlerTransportEvent): boolean
}

export declare class Hello {
  locators(): Array<Locator>
  get whatami(): WhatAmI
  get zid(): string
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class HelloStream {
  [Symbol.asyncIterator](): AsyncGenerator<Hello, void, undefined>
}

export declare class KeyExpr {
  /**
   * Constructs a key expression, rejecting any string that isn't canon.
   *
   * Use `autocanonize` to canonize the input before validating it.
   */
  constructor(expr: string)
  /** Canonizes the passed value before constructing the key expression. */
  static autocanonize(expr: string): KeyExpr
  /** Constructs a key expression from a string. Equivalent to `KeyExpr.new`. */
  static fromStr(expr: string): KeyExpr
  /**
   * Performs string concatenation and returns the result as a `KeyExpr`.
   *
   * You should probably prefer `join` as zenoh may then take
   * advantage of the hierarchical separation it inserts.
   */
  concat(other: string): KeyExpr
  /**
   * Joins both sides, inserting a `/` in between them.
   *
   * This should be your preferred method when concatenating path segments.
   */
  join(other: string): KeyExpr
  /** The canonical string form of this key expression. */
  get asStr(): string
  /**
   * Returns `true` if the key expressions intersect, i.e. there exists at
   * least one key contained in both of the sets defined by `self` and `other`.
   */
  intersects(other: string | KeyExpr): boolean
  /**
   * Returns `true` if `self` includes `other`, i.e. the set defined by `self`
   * contains every key belonging to the set defined by `other`.
   */
  includes(other: string | KeyExpr): boolean
  /** Returns `true` if `self` contains any wildcard character (`**` or `$*`). */
  get isWild(): boolean
}

/**
 * A concrete link within a `Transport`. Zenoh can
 * establish multiple links to the same remote node using different protocols
 * (TCP, UDP, QUIC, ...).
 *
 * Obtained from `SessionInfo.links` or a `LinkEvent`.
 */
export declare class Link {
  /** The Zenoh id of the transport this link belongs to, as a hex string. */
  get zid(): string
  /** The source locator (local endpoint). */
  get src(): Locator
  /** The destination locator (remote endpoint). */
  get dst(): Locator
  /** The group locator (the destination, when the link is multicast), or `null`. */
  get group(): Locator | null
  /** The maximum transmission unit of the link, in bytes. */
  get mtu(): number
  /** Whether the link is streamed. */
  get isStreamed(): boolean
  /** The network interfaces associated with the link. */
  get interfaces(): Array<string>
  /** The authentication identifier used for the link, or `null` if none. */
  get authIdentifier(): string | null
  /**
   * The priority range `{ min, max }` of the link, or `null` if the transport
   * does not support QoS.
   */
  get priorities(): LinkPriorities | null
  /**
   * The reliability level of the link, or `null` if the transport does not
   * support QoS.
   */
  get reliability(): Reliability | null
}

/**
 * An event emitted when a link is added or removed. `kind` is `Put` when the
 * link was added and `Delete` when it was removed.
 *
 * Delivered by a `LinkEventsListener`.
 */
export declare class LinkEvent {
  /** `Put` if the link was added, `Delete` if it was removed. */
  get kind(): SampleKind
  /** The link this event is about. */
  get link(): Link
}

/**
 * A listener that notifies of link lifecycle events (a link being added or
 * removed). Declared via `SessionInfo.linkEventsListener`.
 */
export declare class LinkEventsListener {
  /**
   * The receive end of the listener. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerLinkEvent | RingChannelHandlerLinkEvent
  /**
   * Undeclare this listener. Resolves once undeclaration completes; a second
   * call is a no-op.
   */
  undeclare(): Promise<void>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class LinkEventStream {
  [Symbol.asyncIterator](): AsyncGenerator<LinkEvent, void, undefined>
}

export declare class Liveliness {
  /**
   * Declares a liveliness token on `keyExpr`. The token asserts this session's
   * liveliness for that key expression until it is undeclared or dropped.
   */
  declareToken(keyExpr: string | KeyExpr): Promise<LivelinessToken>
  /** Declares a subscription to liveliness changes matching `keyExpr`. */
  declareSubscriber(keyExpr: string | KeyExpr, options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  /**
   * Queries liveliness tokens matching `keyExpr` and returns the reply handler.
   * The handler completes (disconnects) once the query is resolved.
   */
  get(keyExpr: string | KeyExpr, options?: LivelinessGetOptions | undefined | null): Promise<FifoChannelHandlerReply | RingChannelHandlerReply>
}

/** A subscription to liveliness changes on a key expression. */
export declare class LivelinessSubscriber {
  /** The key expression this subscription matches. */
  get keyExpr(): KeyExpr
  /** The global id of this subscription entity. */
  get id(): EntityGlobalId
  /**
   * The receive end of the subscription. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerSample | RingChannelHandlerSample
  /**
   * Undeclare this subscription. Resolves once undeclaration completes; a
   * second call is a no-op.
   */
  undeclare(): Promise<void>
}

export declare class LivelinessToken {
  /**
   * Undeclare this liveliness token. If the token was already undeclared (or
   * dropped), this is a no-op.
   */
  undeclare(): Promise<void>
}

export declare class Locator {
  /**
   * Constructs a locator from its `<protocol>`, `<address>` and `<metadata>`
   * parts.
   */
  constructor(protocol: string, address: string, metadata: string)
  /** The protocol of this locator. */
  get protocol(): string
  /** The address of this locator. */
  get address(): string
  /** The canonical string form of this locator. */
  get asStr(): string
  /** The metadata view of this locator. */
  metadata(): Metadata
  /** Promotes this locator to an `EndPoint`. */
  toEndpoint(): EndPoint
}

/** A listener that notifies whenever the matching status of its `Publisher`/`Querier` changes (whether matching entities exist) */
export declare class MatchingListener {
  /**
   * The receive end of the listener. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerMatchingStatus | RingChannelHandlerMatchingStatus
  /**
   * Undeclare this matching listener. Resolves once undeclaration completes; a
   * second call is a no-op.
   */
  undeclare(): Promise<void>
}

export declare class MatchingStatus {
  get matching(): boolean
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MatchingStatusStream {
  [Symbol.asyncIterator](): AsyncGenerator<MatchingStatus, void, undefined>
}

export declare class Metadata {
  /** The metadata key for reliability (`"rel"`). */
  static reliabilityKey(): string
  /** The metadata key for priorities (`"prio"`). */
  static prioritiesKey(): string
  /** The metadata key for multistream (`"multistream"`). */
  static multistreamKey(): string
  /** The metadata key for mixed reliability (`"mixed_rel"`). */
  static mixedReliabilityKey(): string
  /** The metadata substring in its canonical string form. */
  asStr(): string
  /** Returns `true` if there is no metadata. */
  isEmpty(): boolean
  /** Returns the first value associated with `key`, if any. */
  get(key: string): string | null
  /** Returns every value associated with `key`. */
  values(key: string): Array<string>
}

/**
 * A missed-samples notification, produced by a `SampleMissListener`.
 * Sample miss detection requires the matching publisher to enable `sampleMissDetection`.
 */
export declare class Miss {
  /** The source of the missed samples. */
  get source(): EntityGlobalId
  /** The number of missed samples. */
  get nb(): number
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MissStream {
  [Symbol.asyncIterator](): AsyncGenerator<Miss, void, undefined>
}

export declare class Parameters {
  /** Creates empty parameters. */
  static empty(): Parameters
  /** Parses parameters from a string in the `a=b;c=d|e;f=g` format. */
  constructor(params: string)
  /** Returns the parameters as their canonical string form. */
  get asStr(): string
  /** Returns `true` if the parameters do not contain anything. */
  get isEmpty(): boolean
  /** Returns `true` if all keys are sorted in alphabetical order. */
  get isOrdered(): boolean
  /** Returns `true` if the parameters contain the specified key. */
  containsKey(key: string): boolean
  /** Returns the value corresponding to the key, if present. */
  get(key: string): string | null
  /** Returns the values corresponding to the key. */
  values(key: string): Array<string>
  /**
   * Inserts a key-value pair, returning the previous value if the key was
   * already present.
   */
  insert(key: string, value: string): string | null
  /** Removes a key, returning its value if the key was present. */
  remove(key: string): string | null
  /** Extends these parameters with the entries of `other`. */
  extend(other: Parameters): void
}

export declare class Publisher {
  /** The key expression this publisher publishes on. */
  get keyExpr(): KeyExpr
  /** The global id of this publisher entity. */
  get id(): EntityGlobalId
  /** The encoding applied to data published by this publisher. */
  get encoding(): Encoding
  /** The congestion control applied when routing this publisher's data. */
  get congestionControl(): CongestionControl
  /** The priority of data published by this publisher. */
  get priority(): Priority
  /** Publishes `payload` on this publisher's key expression. */
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  /** Publishes a delete on this publisher's key expression. */
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  /**
   * The current matching status of this publisher — whether any subscribers
   * match its key expression.
   */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Declares a listener that notifies whenever this publisher's matching status
   * changes (subscribers appear or disappear).
   */
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  /**
   * Undeclare this publisher. Resolves once undeclaration completes; a second
   * call is a no-op.
   */
  undeclare(): Promise<void>
}

export declare class Querier {
  /** The key expression this querier sends queries on. */
  get keyExpr(): KeyExpr
  /** The global id of this querier entity. */
  get id(): EntityGlobalId
  /** The congestion control applied when routing this querier's queries. */
  get congestionControl(): CongestionControl
  /** The priority of this querier's queries. */
  get priority(): Priority
  /**
   * Whether this querier accepts replies whose key expression doesn't match
   * the query.
   */
  get acceptReplies(): ReplyKeyExpr
  /**
   * Sends a query and returns the reply handler. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen via the `handler`
   * option (default: FIFO with capacity 256). Completes (disconnects) once the query is resolved.
   */
  get(options?: QuerierGetOptions | undefined | null): Promise<FifoChannelHandlerReply | RingChannelHandlerReply>
  /**
   * The current matching status of this querier — whether any queryables match
   * its key expression and target.
   */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Declares a listener that notifies whenever this querier's matching status
   * changes (matching queryables appear or disappear).
   */
  matchingListener(options?: MatchingListenerOptions | undefined | null): Promise<MatchingListener>
  /**
   * Undeclare this querier. Resolves once undeclaration completes; a second
   * call is a no-op.
   */
  undeclare(): Promise<void>
}

/**
 * A query received by a `Queryable` — a request this session is expected to
 * answer by sending zero or more replies.
 */
export declare class Query {
  /** The full selector (key expression + parameters) of this query. */
  get selector(): Selector
  /** The key expression part of this query's selector. */
  get keyExpr(): KeyExpr
  /** The parameters part of this query's selector. */
  get parameters(): Parameters
  /** This query's payload, or `null` if it carries none. */
  get payload(): Bytes | null
  /** The encoding of this query's payload, or `null` if it carries no payload. */
  get encoding(): Encoding | null
  /** This query's attachment, or `null` if it carries none. */
  get attachment(): Bytes | null
  /** The source info of this query, or `null` if absent. */
  get sourceInfo(): SourceInfo | null
  /** Whether this query accepts replies whose key expression doesn't match it. */
  get acceptReplies(): ReplyKeyExpr
  /** The priority the reply will be sent with (the query's own priority). */
  get priority(): Priority
  /** The congestion control the reply will be routed with. */
  get congestionControl(): CongestionControl
  /** Whether the reply is sent express (not batched). */
  get express(): boolean
  /** Replies to this query with a `Put` sample on `keyExpr`. */
  reply(keyExpr: string | KeyExpr, payload: string | Uint8Array, options?: ReplyOptions | undefined | null): Promise<void>
  /** Replies to this query with an error payload. */
  replyErr(payload: string | Uint8Array, options?: ReplyErrOptions | undefined | null): Promise<void>
  /** Replies to this query with a `Delete` sample on `keyExpr`. */
  replyDel(keyExpr: string | KeyExpr, options?: ReplyDelOptions | undefined | null): Promise<void>
}

export declare class Queryable {
  /** The key expression this queryable answers queries on. */
  get keyExpr(): KeyExpr
  /** The global id of this queryable entity. */
  get id(): EntityGlobalId
  /**
   * The receive end delivering incoming queries. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerQuery | RingChannelHandlerQuery
  /**
   * Undeclare this queryable. Resolves once undeclaration completes; a second
   * call is a no-op.
   */
  undeclare(): Promise<void>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class QueryStream {
  [Symbol.asyncIterator](): AsyncGenerator<Query, void, undefined>
}

export declare class Reply {
  result(): Sample | ReplyError
  get replierId(): EntityGlobalId | null
}

export declare class ReplyError {
  get encoding(): Encoding
  get payload(): Bytes
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class ReplyStream {
  [Symbol.asyncIterator](): AsyncGenerator<Reply, void, undefined>
}

export declare class RingChannelHandlerHello {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<Hello>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): Hello | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<Hello>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Hello | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Hello | null>
}

export declare class RingChannelHandlerLinkEvent {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<LinkEvent>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): LinkEvent | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<LinkEvent>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<LinkEvent | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<LinkEvent | null>
}

export declare class RingChannelHandlerMatchingStatus {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<MatchingStatus>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): MatchingStatus | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<MatchingStatus>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<MatchingStatus | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<MatchingStatus | null>
}

export declare class RingChannelHandlerMiss {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<Miss>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): Miss | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<Miss>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Miss | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Miss | null>
}

export declare class RingChannelHandlerQuery {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<Query>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): Query | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<Query>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Query | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Query | null>
}

export declare class RingChannelHandlerReply {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<Reply>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): Reply | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<Reply>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Reply | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Reply | null>
}

export declare class RingChannelHandlerSample {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<Sample>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): Sample | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<Sample>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<Sample | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<Sample | null>
}

export declare class RingChannelHandlerTransportEvent {
  /**
   * Receives the next value, resolving when one is available. Rejects once
   * the producer is gone (the ring's strong owner has been dropped).
   */
  recvAsync(): Promise<TransportEvent>
  /**
   * Receives a value without blocking, returning `null` if the ring is
   * currently empty.
   */
  tryRecv(): TransportEvent | null
  /**
   * Resolves with the next value once one is available, rejecting once the
   * producer is gone. zenoh's `recv` is a synchronous blocking call; it is
   * run on a worker thread so the wait never freezes the JS event loop.
   */
  recv(): Promise<TransportEvent>
  /**
   * Resolves with the next value, or `null` if `timeoutMs` milliseconds
   * elapse first. Rejects once the producer is gone. The blocking wait runs
   * on a worker thread.
   */
  recvTimeout(timeoutMs: number): Promise<TransportEvent | null>
  /**
   * Resolves with the next value, or `null` once the wall-clock
   * `deadlineMs` (epoch milliseconds, e.g. from `Date.now()`) passes.
   * Rejects once the producer is gone. The blocking wait runs on a worker
   * thread.
   */
  recvDeadline(deadlineMs: number): Promise<TransportEvent | null>
}

export declare class Sample {
  get payload(): Bytes
  get keyExpr(): KeyExpr
  get kind(): SampleKind
  get encoding(): Encoding
  get timestamp(): Timestamp | null
  get express(): boolean
  get priority(): Priority
  get congestionControl(): CongestionControl
  get reliability(): Reliability
  get attachment(): Bytes | null
  get sourceInfo(): SourceInfo | null
}

/**
 * A listener that notifies of missed samples on a subscription. Declared via
 * `Subscriber.sampleMissListener`; misses are only detected when the matching
 * publisher enables `sampleMissDetection`.
 */
export declare class SampleMissListener {
  /**
   * The receive end of the listener. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerMiss | RingChannelHandlerMiss
  /**
   * Undeclare this sample-miss listener. Resolves once undeclaration completes;
   * a second call is a no-op.
   */
  undeclare(): Promise<void>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class SampleStream {
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

export declare class Scout {
  /**
   * Scout for zenoh processes matching `what` (router/peer/client), using
   * `config` for the multicast settings.
   */
  static scout(what: WhatAmIMatcher, config: Config, options?: ScoutOptions | undefined | null): Promise<Scout>
  /**
   * The receive end delivering `Hello` replies. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at scout time.
   */
  get handler(): FifoChannelHandlerHello | RingChannelHandlerHello
  /** Stop scouting. Idempotent; a second call is a no-op. */
  stop(): void
}

export declare class Selector {
  /** Builds a selector from a key expression and optional parameters. */
  constructor(keyExpr: string | KeyExpr, parameters?: string | undefined | null)
  /** The key expression part of this selector. */
  get keyExpr(): KeyExpr
  /** The parameters part of this selector. */
  get parameters(): Parameters
  /** Deconstructs the selector into its key expression and parameters strings. */
  split(): SelectorParts
}

/**
 * Streaming serializer implementing the Zenoh serialization format.
 *
 * Serializing values one after another is equivalent to serializing a tuple of
 * those values. Call `finish` to consume the serializer and produce the
 * resulting `Bytes`; the serializer cannot be used afterwards.
 */
export declare class Serializer {
  constructor()
  i8(value: number): void
  i16(value: number): void
  i32(value: number): void
  u8(value: number): void
  u16(value: number): void
  u32(value: number): void
  i64(value: bigint): void
  u64(value: bigint): void
  i128(value: bigint): void
  u128(value: bigint): void
  f32(value: number): void
  f64(value: number): void
  bool(value: boolean): void
  string(value: string): void
  /** Serialize a byte blob (LEB128 length prefix + raw bytes). */
  bytes(value: Uint8Array): void
  /** Serialize a sequence of strings (LEB128 count + each string). */
  stringArray(value: Array<string>): void
  int8Array(value: Int8Array): void
  int16Array(value: Int16Array): void
  int32Array(value: Int32Array): void
  uint16Array(value: Uint16Array): void
  uint32Array(value: Uint32Array): void
  float32Array(value: Float32Array): void
  float64Array(value: Float64Array): void
  bigInt64Array(value: BigInt64Array): void
  bigUint64Array(value: BigUint64Array): void
  /**
   * Serialize a non-negative integer as an LEB128 variable-length integer. Used
   * as the length/count prefix for hand-rolled sequences, maps, and sets.
   */
  varint(value: bigint): void
  /**
   * Consume the serializer and return the serialized `Bytes`. Throws if the
   * serializer was already finished.
   */
  finish(): Bytes
}

export declare class Session {
  /** Opens a session with the given configuration. */
  static open(config: Config): Promise<Session>
  /** This session's Zenoh id, as a hex string. */
  get zid(): string
  /** The global id of this session entity. */
  get id(): EntityGlobalId
  /** Whether the session has been closed. */
  get isClosed(): boolean
  /**
   * Mints a new timestamp from the session's clock, stamped with this
   * session's Zenoh id. A fresh value is produced on each call.
   */
  newTimestamp(): Timestamp
  /** The liveliness sub-API for this session (tokens, subscribers, get). */
  liveliness(): Liveliness
  /**
   * The connectivity info sub-API for this session (transports, links, their
   * Zenoh ids, and lifecycle-event listeners).
   */
  info(): SessionInfo
  /**
   * The live configuration sub-API for this session: read current values with
   * `get` / `getPluginConfig`, reconfigure the running session with
   * `insertJson5`.
   */
  config(): SessionConfig
  /** Closes the session, undeclaring everything declared on it. */
  close(): Promise<void>
  /** Publishes `payload` on `keyExpr`. */
  put(keyExpr: string | KeyExpr, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /**
   * Deletes the data matching `keyExpr` (publishes a `Delete` sample).
   *
   * A shortcut for declaring a publisher and calling `delete` on it.
   */
  delete(keyExpr: string | KeyExpr, options?: DeleteOptions | undefined | null): Promise<void>
  /** Declares `keyExpr` on the session, returning an optimized handle to it. */
  declareKeyexpr(keyExpr: string | KeyExpr): Promise<KeyExpr>
  /** Declares a subscription on `keyExpr`. */
  declareSubscriber(keyExpr: string | KeyExpr, options?: SubscriberOptions | undefined | null): Promise<Subscriber>
  /** Declares a publisher on `keyExpr`, fixing its QoS for every publication. */
  declarePublisher(keyExpr: string | KeyExpr, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /** Declares a querier on `keyExpr`, fixing its config for every `get`. */
  declareQuerier(keyExpr: string | KeyExpr, options?: QuerierOptions | undefined | null): Promise<Querier>
  /** Declares a queryable on `keyExpr` that answers matching queries. */
  declareQueryable(keyExpr: string | KeyExpr, options?: QueryableOptions | undefined | null): Promise<Queryable>
  /** Sends a one-shot query on `selector` and returns the reply handler. */
  get(selector: string | KeyExpr | Selector, options?: GetOptions | undefined | null): Promise<FifoChannelHandlerReply | RingChannelHandlerReply>
}

/**
 * Distinct from the `Config` used to *open* a session
 * (an owned, pre-open snapshot): this is a live handle onto the running
 * session's configuration. `get` / `getPluginConfig` read the current values
 * and `insertJson5` reconfigures the session in place.
 */
export declare class SessionConfig {
  /** Reads the configuration value at `key`, returned as a JSON string. */
  get(key: string): string
  /** Inserts the JSON5 `value` at `key`, reconfiguring the running session. */
  insertJson5(key: string, value: string): void
  /** The full current configuration, as a JSON string. */
  toJson(): string
  /** The default timeout applied to queries, in milliseconds. */
  queriesDefaultTimeoutMs(): bigint
  /** Reads the configuration of plugin `pluginName`, returned as a JSON string. */
  getPluginConfig(pluginName: string): string
}

export declare class SessionInfo {
  /** This session's Zenoh id, as a hex string. */
  zid(): Promise<string>
  /**
   * The Zenoh ids of the routers this session is currently connected to (or of
   * the current router, if running inside one), as hex strings.
   */
  routersZid(): Promise<Array<string>>
  /**
   * The Zenoh ids of the peers this session is currently connected to, as hex
   * strings.
   */
  peersZid(): Promise<Array<string>>
  /** The locators this session is listening on. */
  locators(): Promise<Array<Locator>>
  /** The currently-open transports (connections to remote nodes). */
  transports(): Promise<Array<Transport>>
  /** The currently-established links across all transports. */
  links(): Promise<Array<Link>>
  /**
   * Declares a listener for transport lifecycle events (a transport opening or
   * closing). The `handler` option chooses the channel (default: FIFO with
   * capacity 256); `history` replays the currently-open transports on
   * declaration.
   */
  transportEventsListener(options?: TransportEventsListenerOptions | undefined | null): Promise<TransportEventsListener>
  /**
   * Declares a listener for link lifecycle events (a link being added or
   * removed). The `handler` option chooses the channel (default: FIFO with
   * capacity 256); `history` replays the currently-established links on
   * declaration.
   */
  linkEventsListener(options?: LinkEventsListenerOptions | undefined | null): Promise<LinkEventsListener>
}

export declare class SourceInfo {
  constructor(sourceId: EntityGlobalId, sourceSn: number)
  get sourceId(): EntityGlobalId
  get sourceSn(): number
}

export declare class Subscriber {
  /** The key expression this subscription matches. */
  get keyExpr(): KeyExpr
  /** The global id of this subscription entity. */
  get id(): EntityGlobalId
  /**
   * The receive end of the subscription. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerSample | RingChannelHandlerSample
  /**
   * Declares a listener that notifies of samples missed on this subscription.
   *
   * Misses are only detected when the matching publisher enables
   * `sampleMissDetection`. The `handler` option chooses the channel (default:
   * FIFO with capacity 256); it is independent of the
   * subscription's own channel.
   */
  sampleMissListener(options?: SampleMissListenerOptions | undefined | null): Promise<SampleMissListener>
  /**
   * Declares a liveliness subscription that detects publishers matching this
   * subscription's key expression.
   *
   * Only publishers that enable `publisherDetection` are detectable. Resolves
   * to a `LivelinessSubscriber` over the derived detection key expression (a
   * `Put` marks a publisher appearing, a `Delete` one disappearing). The
   * `handler` option chooses the channel (default: FIFO with capacity 256);
   * `history` replays the currently-matching
   * publishers on declaration.
   */
  detectPublishers(options?: LivelinessSubscriberOptions | undefined | null): Promise<LivelinessSubscriber>
  /**
   * Undeclare this subscription. Resolves once undeclaration completes; a
   * second call is a no-op.
   */
  undeclare(): Promise<void>
}

export declare class TimeRange {
  /**
   * The start bound as a string (the time expression), or `null` if the range
   * is unbounded at the start.
   */
  get start(): string | null
  /**
   * The end bound as a string (the time expression), or `null` if the range is
   * unbounded at the end.
   */
  get end(): string | null
  /**
   * Returns `true` if the given instant (UNIX epoch milliseconds, e.g. from
   * `Date.now()`) belongs to this range.
   *
   * If the bounds contain an "offset" time expression (`now(...)`), this
   * resolves them against the current system time on each call.
   */
  contains(epochMillis: number): boolean
}

export declare class Timestamp {
  /**
   * Parse an RFC3339 time representation (`<rfc3339>/<hlc_id_hex>`) into a
   * `Timestamp`.
   */
  static parseRfc3339(s: string): Timestamp
  /**
   * Convert to an RFC3339 time representation with nanoseconds precision.
   * e.g.: `"2024-07-01T13:51:12.129693000Z/33"`.
   */
  toStringRfc3339Lossy(): string
  /** Returns the NTP64 time as its raw `u64` representation. */
  getTime(): bigint
  /** Returns the HLC's unique `id` as a hexadecimal string. */
  getId(): string
  /** Returns the time difference from `other` in milliseconds. */
  getDiffDuration(other: Timestamp): number
}

/** A transport is a connection established to a remote zenoh node. */
export declare class Transport {
  /** The Zenoh id of the remote node, as a hex string. */
  get zid(): string
  /** The type of the remote node (Router, Peer or Client). */
  get whatami(): WhatAmI
  /** Whether this transport supports QoS. */
  get isQos(): boolean
  /** Whether this transport is multicast. */
  get isMulticast(): boolean
}

/**
 * An event emitted when a transport is opened or closed. `kind` is `Put` when
 * the transport opened and `Delete` when it closed.
 *
 * Delivered by a `TransportEventsListener`.
 */
export declare class TransportEvent {
  /** `Put` if the transport opened, `Delete` if it closed. */
  get kind(): SampleKind
  /** The transport this event is about. */
  get transport(): Transport
}

/**
 * A listener that notifies of transport lifecycle events (a transport opening
 * or closing). Declared via `SessionInfo.transportEventsListener`.
 */
export declare class TransportEventsListener {
  /**
   * The receive end of the listener. A `FifoChannelHandler` or
   * `RingChannelHandler` depending on the channel chosen at declare time.
   */
  get handler(): FifoChannelHandlerTransportEvent | RingChannelHandlerTransportEvent
  /**
   * Undeclare this listener. Resolves once undeclaration completes; a second
   * call is a no-op.
   */
  undeclare(): Promise<void>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class TransportEventStream {
  [Symbol.asyncIterator](): AsyncGenerator<TransportEvent, void, undefined>
}

export declare class WhatAmIMatcher {
  static empty(): WhatAmIMatcher
  router(): WhatAmIMatcher
  peer(): WhatAmIMatcher
  client(): WhatAmIMatcher
  get isEmpty(): boolean
  matches(w: WhatAmI): boolean
  toStr(): string
}

export interface CacheConfig {
  maxSamples?: number
  repliesConfig?: RepliesConfig
}

/**
 * Channel selection for a declare call's `handler` field.
 *
 * `capacity` defaults to 256 when omitted.
 */
export interface ChannelConfig {
  kind: ChannelKind
  capacity?: number
}

/** Which channel backs a subscription's handler. */
export type ChannelKind = /** Bounded FIFO: back-pressures the network when full (drops nothing). */
'Fifo'|
/** Bounded ring: keeps the most recent `capacity` samples| dropping oldest. */
'Ring';

/** The congestion control to apply when routing data. */
export type CongestionControl = /** Drop the message when the queue is full. */
'Drop'|
/** Wait for the queue to progress when it is full. */
'Block'|
/** Block only the first message sent with this strategy; drop the rest. */
'BlockFirst';

/** How replies to a query are consolidated before being delivered. */
export type ConsolidationMode = /** Automatic consolidation based on the queryable's preferences. */
'Auto'|
/** No consolidation: multiple samples may be received for the same key. */
'None'|
/** Forward samples immediately| dropping ones superseded by a newer timestamp. */
'Monotonic'|
/** Hold back to send only the samples with the highest timestamp per key. */
'Latest';

/** Options for `Session.delete`. */
export interface DeleteOptions {
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

/**
 * The four string components of an `EndPoint`, as returned by
 * `split`.
 */
export interface EndPointParts {
  protocol: string
  address: string
  metadata: string
  config: string
}

/** Options for `Session.get`. */
export interface GetOptions {
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  /** Timeout in milliseconds. */
  timeout?: number
  payload?: Uint8Array
  encoding?: string
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  /** Channel selection for the reply handler (default: FIFO). */
  handler?: ChannelConfig
}

export interface HeartbeatConfig {
  periodMs: number
  sporadic?: boolean
}

export type HeartbeatMode =  'Heartbeat';

/** Recover the last missed sample by subscribing to publisher heartbeats. */
export interface HeartbeatRecovery {
  mode: HeartbeatMode
}

export interface HistoryConfig {
  detectLatePublishers?: boolean
  maxSamples?: number
  maxAgeSecs?: number
}

/** Options for `SessionInfo.linkEventsListener`. */
export interface LinkEventsListenerOptions {
  /** Send events for the currently-established links before live events. */
  history?: boolean
  /** Channel selection for the listener's handler (default: FIFO). */
  handler?: ChannelConfig
}

/**
 * The priority range `(min, max)` a link is configured with. The numeric
 * priority values correspond to `Priority` but may also
 * include `0` (Control), which is not exposed in that enum.
 */
export interface LinkPriorities {
  min: number
  max: number
}

/** Options for `Liveliness.get`. */
export interface LivelinessGetOptions {
  /** Timeout in milliseconds. */
  timeout?: number
  cancellationToken?: CancellationToken
  /** Channel selection for the reply handler (default: FIFO). */
  handler?: ChannelConfig
}

/** Options for `Liveliness.declareSubscriber`. */
export interface LivelinessSubscriberOptions {
  history?: boolean
  /** Channel selection for the subscriber's handler (default: FIFO). */
  handler?: ChannelConfig
}

/** Restricts which entities (relative to this session) data is routed to/from. */
export type Locality = /** Only entities in the same session. */
'SessionLocal'|
/** Only remote entities (not in the same session). */
'Remote'|
/** Both local and remote entities. */
'Any';

/** Options for `Publisher.matchingListener` — selects the notification channel. */
export interface MatchingListenerOptions {
  /** Channel selection for the listener's handler (default: FIFO). */
  handler?: ChannelConfig
}

export interface MissDetectionConfig {
  heartbeat?: HeartbeatConfig
}

export type PeriodicQueriesMode =  'PeriodicQueries';

/** Recover missed samples by periodically querying for them. */
export interface PeriodicQueriesRecovery {
  mode: PeriodicQueriesMode
  /** Query period in milliseconds. */
  periodMs: number
}

/** The priority of a message when routing. */
export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/**
 * Options for `Publisher.delete`.
 *
 * `sourceInfo` is managed automatically and cannot be set here.
 */
export interface PublisherDeleteOptions {
  timestamp?: Timestamp
  attachment?: Uint8Array
}

/** Options for `Session.declarePublisher`. */
export interface PublisherOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  cache?: CacheConfig
  sampleMissDetection?: MissDetectionConfig
  publisherDetection?: boolean
  publisherDetectionMetadata?: string
}

/**
 * Options for `Publisher.put`.
 *
 * QoS is fixed by the publisher; only per-publication fields appear here.
 * `sourceInfo` is managed automatically for sample-miss sequencing and cannot
 * be set here.
 */
export interface PublisherPutOptions {
  encoding?: string
  timestamp?: Timestamp
  attachment?: Uint8Array
}

/** Options for `Session.put`. */
export interface PutOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  reliability?: Reliability
  allowedDestination?: Locality
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

/** Options for `Querier.get`. */
export interface QuerierGetOptions {
  parameters?: string | Parameters
  payload?: Uint8Array
  encoding?: string
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
  cancellationToken?: CancellationToken
  /** Channel selection for the reply handler (default: FIFO). */
  handler?: ChannelConfig
}

/** Options for `Session.declareQuerier`. */
export interface QuerierOptions {
  target?: QueryTarget
  consolidation?: ConsolidationMode
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
  /** Timeout in milliseconds. */
  timeout?: number
  acceptReplies?: ReplyKeyExpr
}

/** Options for `Session.declareQueryable`. */
export interface QueryableOptions {
  complete?: boolean
  allowedOrigin?: Locality
  /** Channel selection for the queryable's handler (default: FIFO). */
  handler?: ChannelConfig
}

/** The kind of queryables that should be targeted by a query. */
export type QueryTarget = /** Let zenoh find the best matching queryable capable of serving the query. */
'BestMatching'|
/** Deliver the query to all matching queryables. */
'All'|
/** Deliver the query to all matching queryables declared as complete. */
'AllComplete';

/** The reliability to apply when routing data. */
export type Reliability =  'BestEffort'|
'Reliable';

export interface RepliesConfig {
  /** Priority of reply samples (default: `Data`). */
  priority?: Priority
  /** Congestion control for reply samples (default: `Block`). */
  congestionControl?: CongestionControl
  /** When `true`, reply samples are sent unbatched. */
  express?: boolean
}

/** Options for `Query.replyDel` (a `Delete` reply). */
export interface ReplyDelOptions {
  express?: boolean
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

/** Options for `Query.replyErr`. */
export interface ReplyErrOptions {
  encoding?: string
}

/** Whether replies whose key expression doesn't match the query are accepted. */
export type ReplyKeyExpr = /** Accept replies whose key expressions may not match the query. */
'Any'|
/** Accept only replies whose key expressions match the query. */
'MatchingQuery';

/**
 * Options for `Query.reply` (a `Put` reply).
 *
 * `congestionControl` / `priority` are intentionally absent: zenoh deprecated
 * them on replies (they are no-ops — a reply inherits the query's QoS, readable
 * via `Query.congestionControl` / `Query.priority`). `express` still applies.
 */
export interface ReplyOptions {
  encoding?: string
  express?: boolean
  timestamp?: Timestamp
  attachment?: Uint8Array
  sourceInfo?: SourceInfo
}

export type SampleKind =  'Put'|
'Delete';

/** Options for `Subscriber.sampleMissListener` — selects the notification channel. */
export interface SampleMissListenerOptions {
  /** Channel selection for the listener's handler (default: FIFO). */
  handler?: ChannelConfig
}

/** Options for `scout`. */
export interface ScoutOptions {
  /** Channel selection for the `Hello` handler (default: FIFO). */
  handler?: ChannelConfig
}

/** The deconstructed string parts of a `Selector`. */
export interface SelectorParts {
  keyExpr: string
  parameters: string
}

/** Options for `Session.declareSubscriber`. */
export interface SubscriberOptions {
  allowedOrigin?: Locality
  /** Channel selection for the subscription's handler (default: FIFO). */
  handler?: ChannelConfig
  history?: HistoryConfig
  recovery?: PeriodicQueriesRecovery | HeartbeatRecovery
  subscriberDetection?: boolean
  subscriberDetectionMetadata?: string
  queryTimeoutMs?: number
}

/** Options for `SessionInfo.transportEventsListener`. */
export interface TransportEventsListenerOptions {
  /** Send events for the currently-open transports before live events. */
  history?: boolean
  /** Channel selection for the listener's handler (default: FIFO). */
  handler?: ChannelConfig
}

export type WhatAmI =  'Router'|
'Peer'|
'Client';
