/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Zenoh session configuration (mirrors `zenoh::Config`).
 *
 * The configuration tree is opaque; construct it with one of the factory
 * methods. There is intentionally no public constructor.
 */
export declare class Config {
  /** The default configuration (peer mode, default endpoints). */
  static default(): Config
  /** Load configuration from a JSON5 string. */
  static fromJson5(json5: string): Config
  /** Load configuration from a JSON5 file at `path`. */
  static fromFile(path: string): Config
  /**
   * Load configuration from the file pointed to by the `ZENOH_CONFIG`
   * environment variable.
   */
  static fromEnv(): Config
}

/**
 * A `Hello` message received while scouting: a discovered node's identity, kind,
 * and where it can be reached.
 *
 * Fields are exposed as lazy getters, mirroring `zenoh::scouting::Hello`.
 */
export declare class Hello {
  /** The kind of node that sent this `Hello`. */
  get whatami(): WhatAmI
  /** The Zenoh ID of the node, as a hex string. */
  get zid(): string
  /** The locators at which the node can be reached. */
  get locators(): Array<string>
}

/**
 * A Zenoh key expression: a `/`-separated expression that addresses a set of
 * keys (mirrors `zenoh::key_expr::KeyExpr`).
 *
 * To be valid a key expression must be *canon*. Build one from a string with
 * the constructor — which rejects non-canon input — or with
 * [`KeyExpr::autocanonize`], which canonizes the input first.
 *
 * Anywhere this library accepts a key expression you may pass either a
 * `string` or a `KeyExpr`; the getters that expose one hand back a `KeyExpr`.
 */
export declare class KeyExpr {
  /**
   * Build a key expression from a string, failing if it is not a valid, canon
   * key expression. Use [`KeyExpr::autocanonize`] to canonize automatically.
   */
  constructor(keyExpr: string)
  /**
   * Build a key expression from a string, canonizing it first. Fails only if
   * the value is not a valid key expression even after canonization.
   */
  static autocanonize(keyExpr: string): KeyExpr
  /** Whether this key expression and `other` share at least one matching key. */
  intersects(other: string | KeyExpr): boolean
  /** Whether every key matched by `other` is also matched by this expression. */
  includes(other: string | KeyExpr): boolean
  /** Whether this key expression is equal to `other`. */
  equals(other: string | KeyExpr): boolean
  /**
   * Join this key expression with `other`, inserting a `/` between them.
   * Prefer this over [`KeyExpr::concat`] so Zenoh can exploit the separation.
   */
  join(other: string): KeyExpr
  /** Concatenate `other` onto this key expression with no separator inserted. */
  concat(other: string): KeyExpr
  /** The canon string form of this key expression. */
  toString(): string
}

/**
 * Declares liveliness tokens, queries existing ones, and subscribes to
 * liveliness changes (mirrors `zenoh`'s `Liveliness`).
 *
 * A [`LivelinessToken`] is a token whose liveliness is tied to the [`Session`]
 * that declared it and can be monitored by remote applications. Obtain this
 * accessor with [`Session::liveliness`].
 *
 * [`Session`]: crate::session::Session
 */
export declare class Liveliness {
  /**
   * Declare a [`LivelinessToken`] for `key_expr`. The token is seen as alive by
   * any application monitoring it until it is undeclared or dropped (or this
   * session loses connectivity / stops).
   */
  declareToken(keyExpr: string | KeyExpr): Promise<LivelinessToken>
  /**
   * Declare a [`Subscriber`] for liveliness changes matching `key_expr`. Each
   * sample is a `Put` when a matching token appears and a `Delete` when one
   * vanishes. Samples are delivered through a FIFO channel, consumable as an
   * async iterator or via `recv`/`tryRecv`.
   */
  declareSubscriber(keyExpr: string | KeyExpr, options?: LivelinessSubscriberOptions | undefined | null): Promise<Subscriber>
  /**
   * Query liveliness tokens whose key expression matches `key_expr`, receiving
   * the matching tokens' replies through a channel, consumable as an async
   * iterator or via `recv`/`tryRecv`.
   */
  get(keyExpr: string | KeyExpr, options?: LivelinessGetOptions | undefined | null): Promise<Replies>
}

/**
 * A token whose liveliness is tied to the Zenoh [`Session`] that declared it.
 *
 * While the token is not undeclared or dropped — and while the declaring
 * application is alive and has connectivity with the monitoring application —
 * any application monitoring it (via [`Liveliness::declareSubscriber`] or
 * [`Liveliness::get`]) sees it as alive. Tokens are automatically undeclared
 * when dropped. Create one with [`Liveliness::declareToken`].
 *
 * [`Session`]: crate::session::Session
 */
export declare class LivelinessToken {
  /**
   * Undeclare this liveliness token, so monitoring applications stop seeing it
   * as alive. Subsequent calls are no-ops. Resolves synchronously, so awaiting
   * the returned value is optional.
   */
  undeclare(): void
}

/**
 * Notifies of changes to a publisher's [`MatchingStatus`], delivered through a
 * channel. Obtain one from [`Publisher::matchingListener`].
 *
 * Consume it with `for await (const status of listener)`, or pull with
 * `recv()` / `tryRecv()`. The listener is tied to its publisher: if the
 * publisher is undeclared or dropped, iteration ends.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class MatchingListener {
  /**
   * Wait for the next matching-status change, resolving to `null` once the
   * listener is closed.
   */
  recv(): Promise<MatchingStatus | null>
  /**
   * Return a buffered status if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the listener has disconnected,
   * letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): MatchingStatus | null
  /**
   * Undeclare the listener; any buffered statuses are dropped with the handler.
   * Resolves synchronously.
   */
  undeclare(): void
  [Symbol.asyncIterator](): AsyncGenerator<MatchingStatus, void, undefined>
}

/**
 * A publisher bound to a key expression, with QoS fixed at declaration time.
 * Create one with [`Session::declarePublisher`].
 *
 * Every publisher is an advanced publisher (see [`PublisherOptions`]); the
 * publisher owns sequencing, so `put`/`delete` no longer take a `sourceInfo`.
 */
export declare class Publisher {
  /** Publish a `Put` sample to this publisher's key expression. */
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  /** Publish a `Delete` sample to this publisher's key expression. */
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  /** Whether any subscribers currently match this publisher's key expression. */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Declare a [`MatchingListener`] that notifies when this publisher's set of
   * matching subscribers changes. The optional channel `handler` (FIFO or
   * Ring) backs the notifications; defaults to FIFO.
   */
  matchingListener(handler?: ChannelHandler | undefined | null): Promise<MatchingListener>
  /**
   * Undeclare this publisher. Subsequent operations on it will error.
   *
   * Resolves synchronously, so awaiting the returned value is optional.
   */
  undeclare(): void
  /** The key expression this publisher publishes to. */
  get keyExpr(): KeyExpr
  /** The default encoding applied to publications. */
  get encoding(): string
  /** The congestion control strategy. */
  get congestionControl(): CongestionControl
  /** The publication priority. */
  get priority(): Priority
  /** The delivery reliability. */
  get reliability(): Reliability
  /** This publisher's globally-unique entity id. */
  get id(): EntityGlobalId
}

/**
 * A querier bound to a key expression, with query settings fixed at
 * declaration time — the query analog of a [`Publisher`]. Create one with
 * [`Session::declareQuerier`], then issue queries with `get`.
 */
export declare class Querier {
  /**
   * Issue a query on this querier's key expression and receive the matching
   * queryables' replies through a channel, consumable as an async iterator or
   * via `recv`/`tryRecv`.
   */
  get(options?: QuerierGetOptions | undefined | null): Promise<Replies>
  /** Whether any queryables currently match this querier's key expression. */
  matchingStatus(): Promise<MatchingStatus>
  /**
   * Declare a [`MatchingListener`] that notifies when this querier's set of
   * matching queryables changes. The optional channel `handler` (FIFO or Ring)
   * backs the notifications; defaults to FIFO.
   */
  matchingListener(handler?: ChannelHandler | undefined | null): Promise<MatchingListener>
  /**
   * Undeclare this querier. Subsequent operations on it will error.
   *
   * Resolves synchronously, so awaiting the returned value is optional.
   */
  undeclare(): void
  /** The key expression this querier sends queries on. */
  get keyExpr(): KeyExpr
  /** The congestion control strategy applied to queries. */
  get congestionControl(): CongestionControl
  /** The priority of queries. */
  get priority(): Priority
  /** Which reply key expressions this querier accepts. */
  get acceptReplies(): ReplyKeyExpr
  /** This querier's globally-unique entity id. */
  get id(): EntityGlobalId
}

/**
 * A query received by a [`Queryable`], to be answered with `reply` / `replyErr`
 * / `replyDel` (any number of times, including none).
 *
 * The query is finalized when this object is dropped, so keep it alive until
 * you have sent every reply you intend to.
 */
export declare class Query {
  /** The full selector (key expression plus parameters) this query targets. */
  get selector(): string
  /** The key expression this query targets. */
  get keyExpr(): KeyExpr
  /** The selector parameters (the part after `?`), as a raw string. */
  get parameters(): string
  /** The query's payload bytes, if it carried any. */
  get payload(): Buffer | null
  /** The payload encoding, if the query carried a payload. */
  get encoding(): string | null
  /** The query's attachment bytes, if any. */
  get attachment(): Buffer | null
  /** The query's source metadata, if any. */
  get sourceInfo(): SourceInfo | null
  /** Which reply key expressions this query accepts. */
  get acceptsReplies(): ReplyKeyExpr
  /** The priority the query was sent with. */
  get priority(): Priority
  /** The congestion control the query was sent with. */
  get congestionControl(): CongestionControl
  /** Whether the query was sent express (unbatched). */
  get express(): boolean
  /** Reply to this query with a `Put` sample for `key_expr`. */
  reply(keyExpr: string | KeyExpr, payload: string | Uint8Array, options?: ReplyOptions | undefined | null): Promise<void>
  /** Reply to this query with an error response. */
  replyErr(payload: string | Uint8Array, options?: ReplyErrOptions | undefined | null): Promise<void>
  /** Reply to this query with a `Delete` sample for `key_expr`. */
  replyDel(keyExpr: string | KeyExpr, options?: ReplyDelOptions | undefined | null): Promise<void>
}

/**
 * A queryable that delivers [`Query`]s through a channel.
 *
 * Consume it with `for await (const query of queryable)`, or pull queries
 * individually with `recv()` / `tryRecv()`. Iteration ends (yields `null`)
 * once the queryable is undeclared — its buffered queries are dropped with the
 * handler, as in zenoh — or once the session/link closes and any buffered
 * queries have been drained.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Queryable {
  /**
   * Wait for the next query, resolving to `null` once the queryable is
   * undeclared, or once it closes and all buffered queries have been drained.
   */
  recv(): Promise<Query | null>
  /**
   * Return a buffered query if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the queryable has disconnected
   * (undeclared, or the session closed and all buffered queries drained),
   * letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): Query | null
  /**
   * Undeclare the queryable. Iteration / `recv` then end and `tryRecv` throws;
   * any buffered queries are dropped with the handler. Resolves synchronously.
   */
  undeclare(): void
  /** The key expression this queryable answers. */
  get keyExpr(): KeyExpr
  /** This queryable's globally-unique entity id. */
  get id(): EntityGlobalId
  [Symbol.asyncIterator](): AsyncGenerator<Query, void, undefined>
}

/**
 * The replies to a [`Session::get`], delivered through a channel.
 *
 * Consume it with `for await (const reply of replies)`, or pull replies with
 * `recv()` / `tryRecv()`. Each reply is a [`ReplySample`] or a [`ReplyError`] —
 * discriminate with `if (reply.sample)`. Iteration ends (yields `null`) once
 * every queryable has answered or the query times out. A query is not a
 * declared entity, so there is nothing to undeclare.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Replies {
  /**
   * Wait for the next reply, resolving to `null` once the query is complete
   * and all buffered replies have been drained.
   */
  recv(): Promise<ReplySample | ReplyError | null>
  /**
   * Return a buffered reply if one is immediately available, or `null` if none
   * is ready yet. Throws once the query is complete and all replies drained,
   * letting a polling loop tell "nothing yet" apart from "done".
   */
  tryRecv(): ReplySample | ReplyError | null
  [Symbol.asyncIterator](): AsyncGenerator<ReplySample | ReplyError, void, undefined>
}

/**
 * A query reply carrying an error response instead of a sample — mirrors
 * zenoh's `ReplyError` (its `payload` / `encoding`).
 *
 * The other arm of the reply union returned by `get`: `sample` is `null`, so
 * `if (reply.sample)` discriminates it from [`ReplySample`].
 */
export declare class ReplyError {
  /** Always `null` on an error reply — the discriminant against [`ReplySample`]. */
  get sample(): null
  /** The error payload bytes. */
  get payload(): Buffer
  /** The error payload encoding. */
  get encoding(): string
  /** The id of the entity that produced this reply, if known. */
  get replierId(): EntityGlobalId | null
}

/**
 * A query reply carrying a [`Sample`] — the value a queryable returned.
 *
 * One arm of the reply union returned by `get`: `sample` is the queried value.
 * Pairs with [`ReplyError`]; discriminate with `if (reply.sample)`.
 */
export declare class ReplySample {
  /** The sample this reply carries. */
  get sample(): Sample
  /** The id of the entity that produced this reply, if known. */
  get replierId(): EntityGlobalId | null
}

/**
 * A data sample received by a subscriber (or a query reply): the payload plus
 * all of its metadata.
 *
 * Fields are exposed as lazy getters; the payload is only copied into a
 * `Buffer` when accessed.
 */
export declare class Sample {
  /** The key expression this sample was published on. */
  get keyExpr(): KeyExpr
  /** The payload bytes. */
  get payload(): Buffer
  /** Whether this sample is a `Put` or a `Delete`. */
  get kind(): SampleKind
  /** The payload encoding. */
  get encoding(): string
  /** The timestamp attached to the sample, if any. */
  get timestamp(): Timestamp | null
  /** The congestion control strategy the sample was sent with. */
  get congestionControl(): CongestionControl
  /** The priority the sample was sent with. */
  get priority(): Priority
  /** Whether the sample was sent express (unbatched). */
  get express(): boolean
  /** The delivery reliability the sample was sent with. */
  get reliability(): Reliability
  /** The attachment bytes, if any. */
  get attachment(): Buffer | null
  /** The source metadata, if any. */
  get sourceInfo(): SourceInfo | null
}

/**
 * Notifies of samples a subscriber detected as missed, delivered through a
 * channel. Obtain one from [`Subscriber::sampleMissListener`].
 *
 * Consume it with `for await (const miss of listener)`, or pull with
 * `recv()` / `tryRecv()`. The listener is tied to its subscriber: if the
 * subscriber is undeclared or dropped, iteration ends.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class SampleMissListener {
  /**
   * Wait for the next miss notification, resolving to `null` once the listener
   * is closed.
   */
  recv(): Promise<Miss | null>
  /**
   * Return a buffered miss notification if one is immediately available, or
   * `null` if the channel is currently empty. Throws once the listener has
   * disconnected, letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): Miss | null
  /**
   * Undeclare the listener; any buffered notifications are dropped with the
   * handler. Resolves synchronously.
   */
  undeclare(): void
  [Symbol.asyncIterator](): AsyncGenerator<Miss, void, undefined>
}

/**
 * A scout that delivers [`Hello`] messages through a channel.
 *
 * Consume it with `for await (const hello of scout)`, or pull messages
 * individually with `recv()` / `tryRecv()`. Iteration ends (yields `null`)
 * once the scout is stopped — its buffered messages are dropped with the
 * handler, as in zenoh.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Scout {
  /** Wait for the next `Hello`, resolving to `null` once the scout is stopped. */
  recv(): Promise<Hello | null>
  /**
   * Return a buffered `Hello` if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the scout has been stopped, letting
   * a polling loop tell "nothing yet" apart from "stopped".
   */
  tryRecv(): Hello | null
  /**
   * Stop scouting. Iteration / `recv` then end and `tryRecv` throws; any
   * buffered messages are dropped with the handler. Resolves synchronously.
   */
  stop(): void
  [Symbol.asyncIterator](): AsyncGenerator<Hello, void, undefined>
}

/**
 * An open connection to the Zenoh network — the entry point from which every
 * publisher, subscriber, and query is declared. Close it with `close`.
 */
export declare class Session {
  /**
   * Open a session with the given configuration, or the default configuration
   * when omitted.
   */
  static open(config?: Config | undefined | null): Promise<Session>
  /** Close the session, undeclaring every entity declared on it. */
  close(): Promise<void>
  /**
   * Publish a `Put` sample: send `payload` to every subscriber whose key
   * expression matches `key_expr`.
   */
  put(keyExpr: string | KeyExpr, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /**
   * Publish a `Delete` sample for `key_expr`, signalling that the value at that
   * key is no longer valid.
   */
  delete(keyExpr: string | KeyExpr, options?: DeleteOptions | undefined | null): Promise<void>
  /**
   * Query `selector` and receive the matching queryables' replies through a
   * channel, consumable as an async iterator or via `recv`/`tryRecv`.
   */
  get(selector: string, options?: GetOptions | undefined | null): Promise<Replies>
  /**
   * Declare a [`Publisher`] for `key_expr`. Its QoS is fixed at declaration
   * time; per-publication `put`/`delete` can override only payload fields.
   *
   * Every publisher is an advanced publisher (see [`PublisherOptions`]).
   */
  declarePublisher(keyExpr: string | KeyExpr, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /**
   * Declare a [`Subscriber`] for `key_expr`. Samples are delivered through a
   * FIFO channel, consumable as an async iterator or via `recv`/`tryRecv`.
   *
   * Every subscriber is an advanced subscriber (see [`SubscriberOptions`]).
   */
  declareSubscriber(keyExpr: string | KeyExpr, options?: SubscriberOptions | undefined | null): Promise<Subscriber>
  /**
   * Declare a [`Queryable`] for `key_expr`. Queries are delivered through a
   * channel, consumable as an async iterator or via `recv`/`tryRecv`.
   */
  declareQueryable(keyExpr: string | KeyExpr, options?: QueryableOptions | undefined | null): Promise<Queryable>
  /**
   * Declare a [`Querier`] for `key_expr` — a reusable handle for querying that
   * key, with query settings fixed here at declaration time.
   */
  declareQuerier(keyExpr: string | KeyExpr, options?: QuerierOptions | undefined | null): Promise<Querier>
  /**
   * Access this session's liveliness API: declare liveliness tokens, query
   * existing ones, and subscribe to liveliness changes.
   */
  liveliness(): Liveliness
  /** Create a new timestamp using this session's hybrid logical clock. */
  newTimestamp(): Timestamp
  /** Access information about this session and the nodes it is connected to. */
  info(): SessionInfo
  /** The Zenoh ID of this session, as a hex string. */
  get zid(): string
  /** Whether the session has been closed. */
  get isClosed(): boolean
}

/** Information about a [`Session`] and the routers/peers it is connected to. */
export declare class SessionInfo {
  /** The Zenoh ID of this session. */
  zid(): Promise<string>
  /** The Zenoh IDs of the routers this session is currently connected to. */
  routersZid(): Promise<Array<string>>
  /** The Zenoh IDs of the peers this session is currently connected to. */
  peersZid(): Promise<Array<string>>
}

/**
 * A subscriber that delivers [`Sample`]s through a channel.
 *
 * Consume it with `for await (const sample of subscriber)`, or pull samples
 * individually with `recv()` / `tryRecv()`. Iteration ends (yields `null`)
 * once the subscriber is undeclared — its buffered samples are dropped with the
 * handler, as in zenoh — or once the session/link closes and any buffered
 * samples have been drained.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Subscriber {
  /**
   * Wait for the next sample, resolving to `null` once the subscriber is
   * undeclared, or once it closes and all buffered samples have been drained.
   */
  recv(): Promise<Sample | null>
  /**
   * Return a buffered sample if one is immediately available, or `null` if the
   * channel is currently empty. Throws once the subscriber has disconnected
   * (undeclared, or the session closed and all buffered samples drained),
   * letting a polling loop tell "nothing yet" apart from "closed".
   */
  tryRecv(): Sample | null
  /**
   * Undeclare the subscriber. Iteration / `recv` then end and `tryRecv` throws;
   * any buffered samples are dropped with the handler. Resolves synchronously.
   */
  undeclare(): void
  /**
   * Declare a [`SampleMissListener`] for samples this subscriber detected as
   * missed. The optional channel `handler` (FIFO or Ring) backs the
   * notifications; defaults to FIFO.
   *
   * Misses are only detectable from publishers that enable
   * `sampleMissDetection`. Not available on liveliness subscribers.
   */
  sampleMissListener(handler?: ChannelHandler | undefined | null): Promise<SampleMissListener>
  /**
   * Declare a [`Subscriber`] that detects matching advanced publishers through
   * liveliness: each sample is a `Put` when a publisher appears and a `Delete`
   * when it vanishes. The optional channel `handler` defaults to FIFO.
   *
   * Only publishers that enable `publisherDetection` can be detected. Not
   * available on liveliness subscribers.
   */
  detectPublishers(handler?: ChannelHandler | undefined | null): Promise<Subscriber>
  /** The key expression this subscriber is subscribed to. */
  get keyExpr(): KeyExpr
  /** This subscriber's globally-unique entity id. */
  get id(): EntityGlobalId
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

/**
 * Attaches a cache to a publisher so matching subscribers can recover history
 * and/or missed samples from it.
 */
export interface CacheConfig {
  /** How many samples to keep per resource (default: 1). */
  maxSamples?: number
  /** QoS for replies served from the cache. */
  repliesConfig?: RepliesConfig
}

/** Channel handler configuration for a subscriber or listener. */
export interface ChannelHandler {
  /** `Fifo` or `Ring`. */
  kind: ChannelType
  /** Channel capacity. Defaults to Zenoh's default channel size when omitted. */
  capacity?: number
}

/** Which channel kind buffers items for a subscriber or listener. */
export type ChannelType = /** Bounded FIFO queue; applies backpressure to Zenoh when full. */
'Fifo'|
/** Bounded ring buffer; drops the oldest item when full (never blocks). */
'Ring';

/** What a node does when a message reaches it with a full transmission queue. */
export type CongestionControl = /** Drop the message (the default for `put`/`delete`). */
'Drop'|
/** Block the caller until the queue has room. */
'Block'|
/**
 * When transmitting a message in a node with a full queue| the node will wait for queue to progress|
 * but only for the first message sent with this strategy; other messages will be dropped.
 */
'BlockFirst';

/** How replies to a query are consolidated before being delivered. */
export type ConsolidationMode = /** Consolidate automatically| based on the query (default). */
'Auto'|
/** No consolidation: duplicate samples for the same key may be delivered. */
'None'|
/**
 * Forward samples immediately| dropping any with an older-or-equal timestamp
 * already seen for the same key.
 */
'Monotonic'|
/** Hold replies back and deliver only the latest-timestamped sample per key. */
'Latest';

/** Options for [`Session::delete`]. */
export interface DeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the deletion (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the deletion (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/**
 * Globally-unique identifier of a Zenoh entity (a session, publisher, …): the
 * owning session's Zenoh ID together with a session-local entity id.
 */
export interface EntityGlobalId {
  /** Zenoh ID of the owning session, as a hex string. */
  zid: string
  /** Session-local entity id. */
  eid: number
}

/** Options for [`Session::get`]. */
export interface GetOptions {
  /** Payload to send alongside the query. */
  payload?: string | Uint8Array
  /** Encoding of the query payload. */
  encoding?: string
  /** Optional attachment carried alongside the query. */
  attachment?: string | Uint8Array
  /** Congestion control strategy for the query (default: `Block`). */
  congestionControl?: CongestionControl
  /** Priority of the query (default: `Data`). */
  priority?: Priority
  /** When `true`, the query is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Which queryables should answer (default: `BestMatching`). */
  target?: QueryTarget
  /** How replies are consolidated before delivery (default: `Auto`). */
  consolidation?: ConsolidationMode
  /** Restrict which queryables receive the query (default: `Any`). */
  allowedDestination?: Locality
  /** How long to wait for replies, in milliseconds. */
  timeout?: number
  /** Which reply key expressions to accept (default: `MatchingQuery`). */
  acceptReplies?: ReplyKeyExpr
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
  /** Channel handler (FIFO or Ring) backing reply delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/**
 * Periodic heartbeat that advertises the last sample's sequence number, letting
 * subscribers detect and recover a lost *last* sample.
 */
export interface HeartbeatConfig {
  /** Heartbeat period, in milliseconds. */
  periodMs: number
  /**
   * When `true`, the sequence number is advertised only when it changed since
   * the previous period (`sporadicHeartbeat`); otherwise every period
   * (`heartbeat`).
   */
  sporadic?: boolean
}

/**
 * Enables a subscriber to query for historical samples on startup. History can
 * only be served by publishers that enable `cache`.
 */
export interface HistoryConfig {
  /** Detect late-joining publishers (via liveliness) and query their history. */
  detectLatePublishers?: boolean
  /** Query at most this many samples per resource. */
  maxSamples?: number
  /** Query only samples no older than this many seconds. */
  maxAgeSecs?: number
}

/** Options for [`Liveliness::get`]. */
export interface LivelinessGetOptions {
  /**
   * How long to wait for replies, in milliseconds. Defaults to the session's
   * configured query timeout.
   */
  timeout?: number
  /** Channel handler (FIFO or Ring) backing reply delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/** Options for [`Liveliness::declareSubscriber`]. */
export interface LivelinessSubscriberOptions {
  /**
   * When `true`, Zenoh queries the network for the currently live tokens upon
   * declaring the subscriber, delivering each as a `Put` sample. When `false`
   * (the default) it does not — though currently live tokens may still arrive.
   */
  history?: boolean
  /** Channel handler (FIFO or Ring) backing delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/**
 * Restricts which entities a publication reaches (or a subscription accepts),
 * by whether they live in the same session or elsewhere.
 */
export type Locality = /** Only entities in the same session. */
'SessionLocal'|
/** Only remote entities (not in the same session). */
'Remote'|
/** Both local and remote entities (the default). */
'Any';

/**
 * Whether a publisher currently has matching subscribers (or, later, a querier
 * has matching queryables).
 */
export interface MatchingStatus {
  /** `true` if at least one matching entity currently exists. */
  matching: boolean
}

/**
 * A report that a subscriber detected missed samples from a source.
 *
 * Misses are only detected from publishers that enable `sampleMissDetection`.
 */
export interface Miss {
  /** The source (publisher entity) the missed samples were from. */
  source: EntityGlobalId
  /** How many consecutive samples were missed. */
  nb: number
}

/**
 * Enables sample-miss detection on a publisher: each sample is tagged with a
 * per-publisher sequence number, which is what lets subscribers detect misses
 * (`sampleMissListener`) and recover them (`recovery`). The optional
 * `heartbeat` additionally allows the last sample to be recovered.
 */
export interface MissDetectionConfig {
  /** Periodically advertise the last sample's sequence number. */
  heartbeat?: HeartbeatConfig
}

/** Priority of a publication. Listed highest to lowest; `Data` is the default. */
export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/** Options for [`Publisher::delete`]. */
export interface PublisherDeleteOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /**
   * Timestamp to attach; obtain one from [`Session::newTimestamp`]. Overrides
   * the timestamp the publisher attaches automatically.
   */
  timestamp?: Timestamp
}

/**
 * Options for [`Session::declarePublisher`]. These settings are fixed for the
 * publisher's lifetime; per-publication `put`/`delete` may only override
 * payload-level fields (encoding, attachment, …), not QoS.
 *
 * Every publisher is an advanced publisher: `cache`, `sampleMissDetection`, and
 * `publisherDetection` configure the advanced capabilities that matching
 * subscribers rely on for history, recovery, and detection.
 */
export interface PublisherOptions {
  /** Default encoding for publications. */
  encoding?: string
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of publications (default: `Data`). */
  priority?: Priority
  /** When `true`, messages are sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
  /**
   * Cache recent samples so matching subscribers can recover history and/or
   * missed samples from this publisher.
   */
  cache?: CacheConfig
  /**
   * Tag samples with sequence numbers so matching subscribers can detect (and,
   * with `cache`, recover) lost samples.
   */
  sampleMissDetection?: MissDetectionConfig
  /**
   * Advertise this publisher (via liveliness) so subscribers can detect it and
   * request its history.
   */
  publisherDetection?: boolean
  /**
   * Key expression appended to the publisher-detection liveliness token and the
   * cache queryable, used to convey metadata.
   */
  publisherDetectionMetadata?: string
}

/** Options for [`Publisher::put`]. */
export interface PublisherPutOptions {
  /** Encoding of this payload, overriding the publisher's default. */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /**
   * Timestamp to attach; obtain one from [`Session::newTimestamp`]. Overrides
   * the timestamp the publisher attaches automatically.
   */
  timestamp?: Timestamp
}

/** Options for [`Session::put`]. */
export interface PutOptions {
  /** Encoding of the payload (e.g. `"text/plain"`, `"application/json"`). */
  encoding?: string
  /** Optional attachment carried alongside the payload. */
  attachment?: string | Uint8Array
  /** Congestion control strategy (default: `Drop`). */
  congestionControl?: CongestionControl
  /** Priority of the publication (default: `Data`). */
  priority?: Priority
  /** When `true`, the message is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Delivery reliability (default: `Reliable`). */
  reliability?: Reliability
  /** Restrict which matching subscribers receive the data (default: `Any`). */
  allowedDestination?: Locality
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/** Options for [`Querier::get`]. */
export interface QuerierGetOptions {
  /** Selector parameters (the part after `?`) for this query. */
  parameters?: string
  /** Payload to send alongside the query. */
  payload?: string | Uint8Array
  /** Encoding of the query payload. */
  encoding?: string
  /** Optional attachment carried alongside the query. */
  attachment?: string | Uint8Array
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
  /** Channel handler (FIFO or Ring) backing reply delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/**
 * Options for [`Session::declareQuerier`]. These settings are fixed for the
 * querier's lifetime; per-`get` only the payload and parameters may vary.
 */
export interface QuerierOptions {
  /** Congestion control strategy for queries (default: `Block`). */
  congestionControl?: CongestionControl
  /** Priority of queries (default: `Data`). */
  priority?: Priority
  /** When `true`, queries are sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Which queryables should answer (default: `BestMatching`). */
  target?: QueryTarget
  /** How replies are consolidated before delivery (default: `Auto`). */
  consolidation?: ConsolidationMode
  /** Restrict which queryables receive queries (default: `Any`). */
  allowedDestination?: Locality
  /** How long to wait for replies, in milliseconds. */
  timeout?: number
  /** Which reply key expressions to accept (default: `MatchingQuery`). */
  acceptReplies?: ReplyKeyExpr
}

/** Options for [`Session::declareQueryable`]. */
export interface QueryableOptions {
  /**
   * Whether this queryable can answer the full queried key expression on its
   * own; lets queriers using `AllComplete` targeting reach it (default: false).
   */
  complete?: boolean
  /** Restrict which queriers' queries are accepted (default: `Any`). */
  allowedOrigin?: Locality
  /** Channel handler (FIFO or Ring) backing delivery. Defaults to FIFO. */
  handler?: ChannelHandler
}

/** How a query selects which queryables answer it. */
export type QueryTarget = /** Route to the best-matching queryable Zenoh can find (default). */
'BestMatching'|
/** Deliver to every queryable matching the query's key expression. */
'All'|
/** Deliver to every matching queryable declared as `complete`. */
'AllComplete';

/**
 * Configures recovery of detected lost samples. Exactly one mode must be set:
 * `heartbeat` (recover from publisher heartbeats) or `periodicQueriesMs`
 * (recover by polling). They are mutually exclusive — `zenoh-ext` enforces this
 * at the type level, which cannot be expressed in TypeScript, so it is checked
 * at declaration time instead. Recovery can only be achieved by publishers that
 * enable both `cache` and `sampleMissDetection`.
 */
export interface RecoveryConfig {
  /** Recover by subscribing to publisher heartbeats. */
  heartbeat?: boolean
  /** Recover by querying for missed samples every this many milliseconds. */
  periodicQueriesMs?: number
}

/**
 * Reliability of message delivery.
 *
 * **NOTE**: as in Zenoh itself, reliability does not currently trigger wire
 * retransmission; it is a marker that may influence link selection.
 */
export type Reliability = /** Messages may be lost. */
'BestEffort'|
/** Messages are guaranteed to be delivered (the default). */
'Reliable';

/**
 * QoS applied to the samples a publisher's cache sends back when a subscriber
 * queries history or recovers missed samples.
 */
export interface RepliesConfig {
  /** Priority of reply samples (default: `Data`). */
  priority?: Priority
  /** Congestion control for reply samples (default: `Block`). */
  congestionControl?: CongestionControl
  /** When `true`, reply samples are sent unbatched. */
  express?: boolean
}

/** Options for [`Query::replyDel`]. */
export interface ReplyDelOptions {
  /** Optional attachment carried alongside the deletion. */
  attachment?: string | Uint8Array
  /** When `true`, the deletion is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/** Options for [`Query::replyErr`]. */
export interface ReplyErrOptions {
  /** Encoding of the error payload. */
  encoding?: string
}

/** Which reply key expressions a query is willing to accept. */
export type ReplyKeyExpr = /** Accept replies whose key expression need not match the query's. */
'Any'|
/** Accept only replies whose key expression matches the query's (default). */
'MatchingQuery';

/** Options for [`Query::reply`]. */
export interface ReplyOptions {
  /** Encoding of the reply payload. */
  encoding?: string
  /** Optional attachment carried alongside the reply. */
  attachment?: string | Uint8Array
  /** When `true`, the reply is sent unbatched, trading throughput for latency. */
  express?: boolean
  /** Timestamp to attach; obtain one from [`Session::newTimestamp`]. */
  timestamp?: Timestamp
  /** Source metadata (producing entity + sequence number). */
  sourceInfo?: SourceInfo
}

/** Whether a sample was produced by a `put` or a `delete`. */
export type SampleKind = /** Issued by a `put`. */
'Put'|
/** Issued by a `delete`. */
'Delete';

/**
 * Scout for Zenoh nodes in the network.
 *
 * Spawns a task that periodically sends scout messages and delivers the
 * [`Hello`] replies through the returned [`Scout`] handle's channel. Stop it
 * with `Scout.stop()`.
 *
 * # Arguments
 *
 * * `what` - The kinds of node to scout for, as [`WhatAmI`] values that are
 *   folded together. An empty array matches all kinds.
 * * `config` - The [`Config`] to use for scouting.
 * * `handler` - Optional channel handler (FIFO or Ring) backing delivery.
 *   Defaults to FIFO.
 */
export declare function scout(what: Array<WhatAmI>, config: Config, handler?: ChannelHandler | undefined | null): Promise<Scout>

/**
 * Source metadata for a publication: which entity produced the sample and the
 * source's own sequence number for it. Used by advanced pub/sub (e.g. for
 * missing-sample detection); the base primitives just transmit it.
 */
export interface SourceInfo {
  /** Id of the entity that produced the sample. */
  sourceId: EntityGlobalId
  /** The source's sequence number for this sample. */
  sourceSn: number
}

/**
 * Options for [`Session::declareSubscriber`].
 *
 * Every subscriber is an advanced subscriber: `history`, `recovery`, and
 * `subscriberDetection` configure the advanced capabilities that work with
 * matching advanced publishers.
 */
export interface SubscriberOptions {
  /** Restrict which publishers' samples are accepted (default: `Any`). */
  allowedOrigin?: Locality
  /** Channel handler (FIFO or Ring) backing delivery. Defaults to FIFO. */
  handler?: ChannelHandler
  /** Query for historical data on startup (served by publishers that `cache`). */
  history?: HistoryConfig
  /**
   * Ask for retransmission of detected lost samples (served by publishers that
   * enable both `cache` and `sampleMissDetection`).
   */
  recovery?: RecoveryConfig
  /** Advertise this subscriber through liveliness so it can be detected. */
  subscriberDetection?: boolean
  /**
   * Key expression appended to the subscriber-detection liveliness token, used
   * to convey metadata.
   */
  subscriberDetectionMetadata?: string
  /**
   * Timeout for the queries this subscriber issues (history, recovery), in
   * milliseconds.
   */
  queryTimeoutMs?: number
}

/**
 * A Zenoh timestamp: a hybrid-logical-clock time plus the id of the clock that
 * produced it. Obtain one from [`Session::newTimestamp`]; it can then be
 * passed back via the `timestamp` publication option.
 */
export interface Timestamp {
  /** The NTP64-encoded time component (a 64-bit value). */
  time: bigint
  /** The id of the source clock, as a hex string (a Zenoh ID). */
  id: string
}

/**
 * The kind of node a Zenoh process runs as (mirrors `zenoh::config::WhatAmI`).
 *
 * Used both to describe a discovered node (in a [`Hello`]) and to select which
 * kinds to scout for (in [`scout`]).
 */
export type WhatAmI = /**
 * A router: maintains a statically-configured network topology and forwards
 * between nodes.
 */
'Router'|
/** A peer: discovers and connects to other nodes directly (the default mode). */
'Peer'|
/** A client: stays connected to a single gateway node. */
'Client';
