/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Zenoh session configuration (default = peer mode). Wraps `zenoh::Config`.
 *
 * This is the surface deployments use for connectivity — e.g. explicit
 * `connect`/`listen` endpoints when multicast discovery is unavailable between
 * processes. Constructed via the static factories; pass the result to `open()`.
 */
export declare class Config {
  /** Default configuration (peer mode). */
  static default(): Config
  /** Parse a JSON5 (or plain JSON, a subset of JSON5) configuration string. */
  static fromJson5(json5: string): Config
  /** Load configuration from a file path (JSON5/JSON/YAML per extension). */
  static fromFile(path: string): Config
  /** Load configuration from the file referenced by the `ZENOH_CONFIG` env var. */
  static fromEnv(): Config
  /**
   * Insert or override a value at a key path; `value` is a JSON5 fragment.
   * e.g. `insertJson5("scouting/multicast/enabled", "false")`.
   */
  insertJson5(key: string, value: string): void
  /** Serialize the configuration to a JSON string (private fields elided). */
  toString(): string
}

/**
 * A declared publisher. The underlying `Publisher<'static>` is kept behind an
 * `Arc` so `put`/`delete` can borrow it across the await on a shared `&self`,
 * and behind a `Mutex<Option<…>>` so `undeclare` can take ownership.
 */
export declare class Publisher {
  get keyExpr(): string
  put(payload: string | Uint8Array, options?: PublisherPutOptions | undefined | null): Promise<void>
  delete(options?: PublisherDeleteOptions | undefined | null): Promise<void>
  undeclare(): Promise<void>
}

export declare class Session {
  /** Zenoh ID of this session. */
  get zid(): string
  /** This session's view of the network (its zid plus connected routers/peers). */
  info(): Promise<SessionInfo>
  /** Session-level publication. */
  put(keyExpr: string, payload: string | Uint8Array, options?: PutOptions | undefined | null): Promise<void>
  /** Session-level delete (tombstone). */
  delete(keyExpr: string, options?: DeleteOptions | undefined | null): Promise<void>
  /**
   * Declare a publisher. QoS / addressing is fixed here; per-message overrides go
   * on `publisher.put()`.
   */
  declarePublisher(keyExpr: string, options?: PublisherOptions | undefined | null): Promise<Publisher>
  /**
   * Declare a channel-mode subscriber. The returned object is an async iterable:
   * `for await (const sample of sub) { ... }`.
   */
  declareSubscriber(keyExpr: string): Promise<Subscriber>
  close(): Promise<void>
}

/**
 * Channel-mode subscriber: an async iterator over Zenoh's FIFO handler.
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class Subscriber {
  get keyExpr(): string
  /** Pull one sample, or `null` once the subscription is closed/undeclared. */
  receive(): Promise<Sample | null>
  undeclare(): Promise<void>
  [Symbol.asyncIterator](): AsyncGenerator<Sample, void, undefined>
}

export type CongestionControl =  'Drop'|
'Block';

/**
 * QoS / metadata overrides for a session-level `delete` (no payload, so no
 * encoding). (`timestamp` and `reliability` are deferred — see SPEC §9/§15.)
 */
export interface DeleteOptions {
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  attachment?: string | Uint8Array
  allowedDestination?: Locality
}

export type Locality =  'SessionLocal'|
'Remote'|
'Any';

/**
 * Open a Zenoh session (default = peer mode).
 *
 * `config` accepts a JSON5 string (a subset; plain JSON works too), a `Config`
 * instance, or nothing (default peer config). The string form is a convenience
 * over `Config.fromJson5`.
 */
export declare function open(config?: string | Config | undefined | null): Promise<Session>

export type Priority =  'RealTime'|
'InteractiveHigh'|
'InteractiveLow'|
'DataHigh'|
'Data'|
'DataLow'|
'Background';

/** Per-message overrides for `publisher.delete()`. */
export interface PublisherDeleteOptions {
  attachment?: string | Uint8Array
}

/** QoS + addressing fixed on the publisher at declare time. */
export interface PublisherOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  allowedDestination?: Locality
}

/**
 * Per-message overrides for `publisher.put()`. QoS is fixed at declare time, so
 * only content/metadata vary here. (`timestamp` override lands in a later slice —
 * it needs construction of a Zenoh `Timestamp` from JS.)
 */
export interface PublisherPutOptions {
  encoding?: string
  attachment?: string | Uint8Array
}

/**
 * QoS / metadata overrides for a session-level `put`. Unlike a declared
 * publisher (whose QoS is fixed), session `put` accepts per-call overrides.
 * (`timestamp` and `reliability` are deferred — see SPEC §9/§15.)
 */
export interface PutOptions {
  encoding?: string
  congestionControl?: CongestionControl
  priority?: Priority
  express?: boolean
  attachment?: string | Uint8Array
  allowedDestination?: Locality
}

/**
 * A sample delivered to JS. `#[napi(object)]` makes it a plain JS object, mapped
 * field by field from Zenoh's getters. Only `unstable`-gated fields
 * (`reliability`, `sourceInfo`) are omitted.
 */
export interface Sample {
  keyExpr: string
  payload: Uint8Array
  kind: SampleKind
  encoding: string
  timestamp?: Timestamp
  congestionControl: CongestionControl
  priority: Priority
  express: boolean
  attachment?: Uint8Array
}

export type SampleKind =  'Put'|
'Delete';

/** Snapshot of the session's view of the network, from `session.info()`. */
export interface SessionInfo {
  /** Zenoh ID of this session. */
  zid: string
  /** Zenoh IDs of the routers this session is connected to. */
  routers: Array<string>
  /** Zenoh IDs of the peers this session is connected to. */
  peers: Array<string>
}

/**
 * Zenoh `Timestamp` as plain data. Convert to a JS `Date` with the
 * `ntp64ToDate(ntp64)` helper (lives in the JS layer) to keep `Sample` a POJO.
 */
export interface Timestamp {
  /** zid of the timestamp source. */
  id: string
  /** Raw NTP64. */
  ntp64: bigint
}
